version: "3"
services:
  app:
    container_name: vue-books-app
    build:
      context: ./../
      dockerfile: .docker/Dockerfile
      target: prod
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:9000}
    ports:
      - "8080:8080"